services:
  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      LOCALSTACK_AUTH_TOKEN: "eds"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: eds
      MYSQL_USER: eds
      MYSQL_PASSWORD: eds
      MYSQL_DATABASE: eds
    ports:
      - 13306:3306
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: eds
      POSTGRES_PASSWORD: eds
      POSTGRES_DB: eds
    ports:
      - 15432:5432
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    stdin_open: true
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=Asdf1234!
      - ACCEPT_EULA=Y
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      - MSSQL_LOG_DIR=/var/opt/mssql/log
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
    volumes:
      - ./sqlserver-data:/var/opt/mssql
