services:
  s3:
    image: localstack/localstack:s3-latest
    hostname: s3
    ports:
      - 4566:4566
    environment:
      LOCALSTACK_AUTH_TOKEN: "eds"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: eds
      MYSQL_USER: eds
      MYSQL_PASSWORD: Asdf1234!
      MYSQL_DATABASE: eds
    ports:
      - 13306:3306
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: eds
      POSTGRES_PASSWORD: Asdf1234!
      POSTGRES_DB: eds
    ports:
      - 15432:5432
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    stdin_open: true
    user: root
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=Asdf1234!
      - ACCEPT_EULA=Y
      - MSSQL_DATA_DIR=/var/opt/mssql/data
  init-kafka:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    restart: no
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic eds --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
  init-s3:
    image: localstack/localstack
    depends_on:
      - s3
    entrypoint: ["/bin/sh", "-c"]
    restart: no
    command: |
      "awslocal s3api create-bucket --bucket eds --endpoint-url http://s3:4566"
