version: '3.7'
services:
    postgres:
        image: postgres:16.3
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=shopmonkey
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    mssql:
      image: mcr.microsoft.com/azure-sql-edge
      stdin_open: true
      ports:
        - "1433:1433"
      environment:
        - MSSQL_SA_PASSWORD=Asdf1234!
        - ACCEPT_EULA=Y
        - MSSQL_DATA_DIR=/var/opt/mssql/data
        - MSSQL_LOG_DIR=/var/opt/mssql/log
        - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
      volumes:
        - ./sqlserver-data:/var/opt/mssql  
