// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: shopmonkey/edsv4prototype/v1/stream.proto

package edsv4prototypev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdsV4PrototypeService_Fetch_FullMethodName                   = "/shopmonkey.edsv4prototype.v1.EdsV4PrototypeService/Fetch"
	EdsV4PrototypeService_Log_FullMethodName                     = "/shopmonkey.edsv4prototype.v1.EdsV4PrototypeService/Log"
	EdsV4PrototypeService_Control_FullMethodName                 = "/shopmonkey.edsv4prototype.v1.EdsV4PrototypeService/Control"
	EdsV4PrototypeService_PublishSendLogsComplete_FullMethodName = "/shopmonkey.edsv4prototype.v1.EdsV4PrototypeService/PublishSendLogsComplete"
	EdsV4PrototypeService_SendStatus_FullMethodName              = "/shopmonkey.edsv4prototype.v1.EdsV4PrototypeService/SendStatus"
	EdsV4PrototypeService_ImportResult_FullMethodName            = "/shopmonkey.edsv4prototype.v1.EdsV4PrototypeService/ImportResult"
)

// EdsV4PrototypeServiceClient is the client API for EdsV4PrototypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdsV4PrototypeServiceClient interface {
	// needs stream to handle large batches of messages
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	// Control is used for syncronous commands pushed to the client
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlReply, ControlCommand], error)
	PublishSendLogsComplete(ctx context.Context, in *PSLCRequest, opts ...grpc.CallOption) (*PSLCResponse, error)
	SendStatus(ctx context.Context, in *SendStatusRequest, opts ...grpc.CallOption) (*SendStatusResponse, error)
	ImportResult(ctx context.Context, in *ImportResultRequest, opts ...grpc.CallOption) (*ImportResultResponse, error)
}

type edsV4PrototypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdsV4PrototypeServiceClient(cc grpc.ClientConnInterface) EdsV4PrototypeServiceClient {
	return &edsV4PrototypeServiceClient{cc}
}

func (c *edsV4PrototypeServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EdsV4PrototypeService_ServiceDesc.Streams[0], EdsV4PrototypeService_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdsV4PrototypeService_FetchClient = grpc.ServerStreamingClient[FetchResponse]

func (c *edsV4PrototypeServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, EdsV4PrototypeService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edsV4PrototypeServiceClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlReply, ControlCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EdsV4PrototypeService_ServiceDesc.Streams[1], EdsV4PrototypeService_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlReply, ControlCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdsV4PrototypeService_ControlClient = grpc.BidiStreamingClient[ControlReply, ControlCommand]

func (c *edsV4PrototypeServiceClient) PublishSendLogsComplete(ctx context.Context, in *PSLCRequest, opts ...grpc.CallOption) (*PSLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PSLCResponse)
	err := c.cc.Invoke(ctx, EdsV4PrototypeService_PublishSendLogsComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edsV4PrototypeServiceClient) SendStatus(ctx context.Context, in *SendStatusRequest, opts ...grpc.CallOption) (*SendStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendStatusResponse)
	err := c.cc.Invoke(ctx, EdsV4PrototypeService_SendStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edsV4PrototypeServiceClient) ImportResult(ctx context.Context, in *ImportResultRequest, opts ...grpc.CallOption) (*ImportResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportResultResponse)
	err := c.cc.Invoke(ctx, EdsV4PrototypeService_ImportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdsV4PrototypeServiceServer is the server API for EdsV4PrototypeService service.
// All implementations must embed UnimplementedEdsV4PrototypeServiceServer
// for forward compatibility.
type EdsV4PrototypeServiceServer interface {
	// needs stream to handle large batches of messages
	Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error
	Log(context.Context, *LogRequest) (*LogResponse, error)
	// Control is used for syncronous commands pushed to the client
	Control(grpc.BidiStreamingServer[ControlReply, ControlCommand]) error
	PublishSendLogsComplete(context.Context, *PSLCRequest) (*PSLCResponse, error)
	SendStatus(context.Context, *SendStatusRequest) (*SendStatusResponse, error)
	ImportResult(context.Context, *ImportResultRequest) (*ImportResultResponse, error)
	mustEmbedUnimplementedEdsV4PrototypeServiceServer()
}

// UnimplementedEdsV4PrototypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdsV4PrototypeServiceServer struct{}

func (UnimplementedEdsV4PrototypeServiceServer) Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error {
	return status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedEdsV4PrototypeServiceServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedEdsV4PrototypeServiceServer) Control(grpc.BidiStreamingServer[ControlReply, ControlCommand]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedEdsV4PrototypeServiceServer) PublishSendLogsComplete(context.Context, *PSLCRequest) (*PSLCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSendLogsComplete not implemented")
}
func (UnimplementedEdsV4PrototypeServiceServer) SendStatus(context.Context, *SendStatusRequest) (*SendStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendStatus not implemented")
}
func (UnimplementedEdsV4PrototypeServiceServer) ImportResult(context.Context, *ImportResultRequest) (*ImportResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportResult not implemented")
}
func (UnimplementedEdsV4PrototypeServiceServer) mustEmbedUnimplementedEdsV4PrototypeServiceServer() {}
func (UnimplementedEdsV4PrototypeServiceServer) testEmbeddedByValue()                               {}

// UnsafeEdsV4PrototypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdsV4PrototypeServiceServer will
// result in compilation errors.
type UnsafeEdsV4PrototypeServiceServer interface {
	mustEmbedUnimplementedEdsV4PrototypeServiceServer()
}

func RegisterEdsV4PrototypeServiceServer(s grpc.ServiceRegistrar, srv EdsV4PrototypeServiceServer) {
	// If the following call panics, it indicates UnimplementedEdsV4PrototypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdsV4PrototypeService_ServiceDesc, srv)
}

func _EdsV4PrototypeService_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EdsV4PrototypeServiceServer).Fetch(m, &grpc.GenericServerStream[FetchRequest, FetchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdsV4PrototypeService_FetchServer = grpc.ServerStreamingServer[FetchResponse]

func _EdsV4PrototypeService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdsV4PrototypeServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdsV4PrototypeService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdsV4PrototypeServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdsV4PrototypeService_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EdsV4PrototypeServiceServer).Control(&grpc.GenericServerStream[ControlReply, ControlCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdsV4PrototypeService_ControlServer = grpc.BidiStreamingServer[ControlReply, ControlCommand]

func _EdsV4PrototypeService_PublishSendLogsComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PSLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdsV4PrototypeServiceServer).PublishSendLogsComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdsV4PrototypeService_PublishSendLogsComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdsV4PrototypeServiceServer).PublishSendLogsComplete(ctx, req.(*PSLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdsV4PrototypeService_SendStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdsV4PrototypeServiceServer).SendStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdsV4PrototypeService_SendStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdsV4PrototypeServiceServer).SendStatus(ctx, req.(*SendStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdsV4PrototypeService_ImportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdsV4PrototypeServiceServer).ImportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdsV4PrototypeService_ImportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdsV4PrototypeServiceServer).ImportResult(ctx, req.(*ImportResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdsV4PrototypeService_ServiceDesc is the grpc.ServiceDesc for EdsV4PrototypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdsV4PrototypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shopmonkey.edsv4prototype.v1.EdsV4PrototypeService",
	HandlerType: (*EdsV4PrototypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _EdsV4PrototypeService_Log_Handler,
		},
		{
			MethodName: "PublishSendLogsComplete",
			Handler:    _EdsV4PrototypeService_PublishSendLogsComplete_Handler,
		},
		{
			MethodName: "SendStatus",
			Handler:    _EdsV4PrototypeService_SendStatus_Handler,
		},
		{
			MethodName: "ImportResult",
			Handler:    _EdsV4PrototypeService_ImportResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fetch",
			Handler:       _EdsV4PrototypeService_Fetch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Control",
			Handler:       _EdsV4PrototypeService_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "shopmonkey/edsv4prototype/v1/stream.proto",
}
