// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shopmonkey/transmission/v1/stream.proto

package transmissionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxCount      int32                  `protobuf:"varint,1,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	EdsId         string                 `protobuf:"bytes,3,opt,name=eds_id,json=edsId,proto3" json:"eds_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *FetchRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *FetchRequest) GetEdsId() string {
	if x != nil {
		return x.EdsId
	}
	return ""
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChangeMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetMessages() []*ChangeMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChangeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMessage) Reset() {
	*x = ChangeMessage{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMessage) ProtoMessage() {}

func (x *ChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMessage.ProtoReflect.Descriptor instead.
func (*ChangeMessage) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	EdsId         string                 `protobuf:"bytes,2,opt,name=eds_id,json=edsId,proto3" json:"eds_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *LogRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *LogRequest) GetEdsId() string {
	if x != nil {
		return x.EdsId
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{4}
}

type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdsId         string                 `protobuf:"bytes,1,opt,name=eds_id,json=edsId,proto3" json:"eds_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{5}
}

func (x *ControlRequest) GetEdsId() string {
	if x != nil {
		return x.EdsId
	}
	return ""
}

func (x *ControlRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{6}
}

func (x *ControlResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ControlResponse) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_shopmonkey_transmission_v1_stream_proto protoreflect.FileDescriptor

const file_shopmonkey_transmission_v1_stream_proto_rawDesc = "" +
	"\n" +
	"'shopmonkey/transmission/v1/stream.proto\x12\x1ashopmonkey.transmission.v1\x1a\x1cgoogle/protobuf/struct.proto\"a\n" +
	"\fFetchRequest\x12\x1b\n" +
	"\tmax_count\x18\x01 \x01(\x05R\bmaxCount\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\x12\x15\n" +
	"\x06eds_id\x18\x03 \x01(\tR\x05edsId\"V\n" +
	"\rFetchResponse\x12E\n" +
	"\bmessages\x18\x01 \x03(\v2).shopmonkey.transmission.v1.ChangeMessageR\bmessages\")\n" +
	"\rChangeMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"7\n" +
	"\n" +
	"LogRequest\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\x12\x15\n" +
	"\x06eds_id\x18\x02 \x01(\tR\x05edsId\"\r\n" +
	"\vLogResponse\"F\n" +
	"\x0eControlRequest\x12\x15\n" +
	"\x06eds_id\x18\x01 \x01(\tR\x05edsId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\\\n" +
	"\x0fControlResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload2\xb3\x02\n" +
	"\x13TransmissionService\x12^\n" +
	"\x05Fetch\x12(.shopmonkey.transmission.v1.FetchRequest\x1a).shopmonkey.transmission.v1.FetchResponse0\x01\x12V\n" +
	"\x03Log\x12&.shopmonkey.transmission.v1.LogRequest\x1a'.shopmonkey.transmission.v1.LogResponse\x12d\n" +
	"\aControl\x12*.shopmonkey.transmission.v1.ControlRequest\x1a+.shopmonkey.transmission.v1.ControlResponse0\x01B@Z>github.com/shopmonkeyus/eds/pkg/transmission/v1;transmissionv1b\x06proto3"

var (
	file_shopmonkey_transmission_v1_stream_proto_rawDescOnce sync.Once
	file_shopmonkey_transmission_v1_stream_proto_rawDescData []byte
)

func file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP() []byte {
	file_shopmonkey_transmission_v1_stream_proto_rawDescOnce.Do(func() {
		file_shopmonkey_transmission_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shopmonkey_transmission_v1_stream_proto_rawDesc), len(file_shopmonkey_transmission_v1_stream_proto_rawDesc)))
	})
	return file_shopmonkey_transmission_v1_stream_proto_rawDescData
}

var file_shopmonkey_transmission_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shopmonkey_transmission_v1_stream_proto_goTypes = []any{
	(*FetchRequest)(nil),    // 0: shopmonkey.transmission.v1.FetchRequest
	(*FetchResponse)(nil),   // 1: shopmonkey.transmission.v1.FetchResponse
	(*ChangeMessage)(nil),   // 2: shopmonkey.transmission.v1.ChangeMessage
	(*LogRequest)(nil),      // 3: shopmonkey.transmission.v1.LogRequest
	(*LogResponse)(nil),     // 4: shopmonkey.transmission.v1.LogResponse
	(*ControlRequest)(nil),  // 5: shopmonkey.transmission.v1.ControlRequest
	(*ControlResponse)(nil), // 6: shopmonkey.transmission.v1.ControlResponse
	(*structpb.Struct)(nil), // 7: google.protobuf.Struct
}
var file_shopmonkey_transmission_v1_stream_proto_depIdxs = []int32{
	2, // 0: shopmonkey.transmission.v1.FetchResponse.messages:type_name -> shopmonkey.transmission.v1.ChangeMessage
	7, // 1: shopmonkey.transmission.v1.ControlResponse.payload:type_name -> google.protobuf.Struct
	0, // 2: shopmonkey.transmission.v1.TransmissionService.Fetch:input_type -> shopmonkey.transmission.v1.FetchRequest
	3, // 3: shopmonkey.transmission.v1.TransmissionService.Log:input_type -> shopmonkey.transmission.v1.LogRequest
	5, // 4: shopmonkey.transmission.v1.TransmissionService.Control:input_type -> shopmonkey.transmission.v1.ControlRequest
	1, // 5: shopmonkey.transmission.v1.TransmissionService.Fetch:output_type -> shopmonkey.transmission.v1.FetchResponse
	4, // 6: shopmonkey.transmission.v1.TransmissionService.Log:output_type -> shopmonkey.transmission.v1.LogResponse
	6, // 7: shopmonkey.transmission.v1.TransmissionService.Control:output_type -> shopmonkey.transmission.v1.ControlResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shopmonkey_transmission_v1_stream_proto_init() }
func file_shopmonkey_transmission_v1_stream_proto_init() {
	if File_shopmonkey_transmission_v1_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shopmonkey_transmission_v1_stream_proto_rawDesc), len(file_shopmonkey_transmission_v1_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopmonkey_transmission_v1_stream_proto_goTypes,
		DependencyIndexes: file_shopmonkey_transmission_v1_stream_proto_depIdxs,
		MessageInfos:      file_shopmonkey_transmission_v1_stream_proto_msgTypes,
	}.Build()
	File_shopmonkey_transmission_v1_stream_proto = out.File
	file_shopmonkey_transmission_v1_stream_proto_goTypes = nil
	file_shopmonkey_transmission_v1_stream_proto_depIdxs = nil
}
