// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shopmonkey/transmission/v1/stream.proto

package transmissionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusAction int32

const (
	StatusAction_STATUS_ACTION_UNSPECIFIED StatusAction = 0
	StatusAction_STATUS_ACTION_RESTART     StatusAction = 1
	StatusAction_STATUS_ACTION_UPGRADE     StatusAction = 2
	StatusAction_STATUS_ACTION_IMPORT      StatusAction = 3
)

// Enum value maps for StatusAction.
var (
	StatusAction_name = map[int32]string{
		0: "STATUS_ACTION_UNSPECIFIED",
		1: "STATUS_ACTION_RESTART",
		2: "STATUS_ACTION_UPGRADE",
		3: "STATUS_ACTION_IMPORT",
	}
	StatusAction_value = map[string]int32{
		"STATUS_ACTION_UNSPECIFIED": 0,
		"STATUS_ACTION_RESTART":     1,
		"STATUS_ACTION_UPGRADE":     2,
		"STATUS_ACTION_IMPORT":      3,
	}
)

func (x StatusAction) Enum() *StatusAction {
	p := new(StatusAction)
	*p = x
	return p
}

func (x StatusAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusAction) Descriptor() protoreflect.EnumDescriptor {
	return file_shopmonkey_transmission_v1_stream_proto_enumTypes[0].Descriptor()
}

func (StatusAction) Type() protoreflect.EnumType {
	return &file_shopmonkey_transmission_v1_stream_proto_enumTypes[0]
}

func (x StatusAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusAction.Descriptor instead.
func (StatusAction) EnumDescriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{0}
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxCount      int32                  `protobuf:"varint,1,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	EdsId         string                 `protobuf:"bytes,3,opt,name=eds_id,json=edsId,proto3" json:"eds_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *FetchRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *FetchRequest) GetEdsId() string {
	if x != nil {
		return x.EdsId
	}
	return ""
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChangeMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetMessages() []*ChangeMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChangeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMessage) Reset() {
	*x = ChangeMessage{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMessage) ProtoMessage() {}

func (x *ChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMessage.ProtoReflect.Descriptor instead.
func (*ChangeMessage) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	EdsId         string                 `protobuf:"bytes,2,opt,name=eds_id,json=edsId,proto3" json:"eds_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *LogRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *LogRequest) GetEdsId() string {
	if x != nil {
		return x.EdsId
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{4}
}

// Control replies: EDS -> transmission
type ControlReply struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EdsId     string                 `protobuf:"bytes,1,opt,name=eds_id,json=edsId,proto3" json:"eds_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Reply:
	//
	//	*ControlReply_StreamAttach
	//	*ControlReply_Restart
	//	*ControlReply_Shutdown
	//	*ControlReply_Pause
	//	*ControlReply_Unpause
	//	*ControlReply_Upgrade
	//	*ControlReply_Sendlogs
	//	*ControlReply_Configure
	//	*ControlReply_Import
	//	*ControlReply_DriverConfig
	//	*ControlReply_Validate
	Reply         isControlReply_Reply `protobuf_oneof:"reply"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlReply) Reset() {
	*x = ControlReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlReply) ProtoMessage() {}

func (x *ControlReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlReply.ProtoReflect.Descriptor instead.
func (*ControlReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{5}
}

func (x *ControlReply) GetEdsId() string {
	if x != nil {
		return x.EdsId
	}
	return ""
}

func (x *ControlReply) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlReply) GetReply() isControlReply_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *ControlReply) GetStreamAttach() *StreamAttach {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_StreamAttach); ok {
			return x.StreamAttach
		}
	}
	return nil
}

func (x *ControlReply) GetRestart() *RestartReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *ControlReply) GetShutdown() *ShutdownReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ControlReply) GetPause() *PauseReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *ControlReply) GetUnpause() *UnpauseReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Unpause); ok {
			return x.Unpause
		}
	}
	return nil
}

func (x *ControlReply) GetUpgrade() *UpgradeReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Upgrade); ok {
			return x.Upgrade
		}
	}
	return nil
}

func (x *ControlReply) GetSendlogs() *SendLogsReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Sendlogs); ok {
			return x.Sendlogs
		}
	}
	return nil
}

func (x *ControlReply) GetConfigure() *ConfigureReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Configure); ok {
			return x.Configure
		}
	}
	return nil
}

func (x *ControlReply) GetImport() *ImportReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Import); ok {
			return x.Import
		}
	}
	return nil
}

func (x *ControlReply) GetDriverConfig() *DriverConfigReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_DriverConfig); ok {
			return x.DriverConfig
		}
	}
	return nil
}

func (x *ControlReply) GetValidate() *ValidateReply {
	if x != nil {
		if x, ok := x.Reply.(*ControlReply_Validate); ok {
			return x.Validate
		}
	}
	return nil
}

type isControlReply_Reply interface {
	isControlReply_Reply()
}

type ControlReply_StreamAttach struct {
	StreamAttach *StreamAttach `protobuf:"bytes,3,opt,name=stream_attach,json=streamAttach,proto3,oneof"`
}

type ControlReply_Restart struct {
	Restart *RestartReply `protobuf:"bytes,4,opt,name=restart,proto3,oneof"`
}

type ControlReply_Shutdown struct {
	Shutdown *ShutdownReply `protobuf:"bytes,5,opt,name=shutdown,proto3,oneof"`
}

type ControlReply_Pause struct {
	Pause *PauseReply `protobuf:"bytes,6,opt,name=pause,proto3,oneof"`
}

type ControlReply_Unpause struct {
	Unpause *UnpauseReply `protobuf:"bytes,7,opt,name=unpause,proto3,oneof"`
}

type ControlReply_Upgrade struct {
	Upgrade *UpgradeReply `protobuf:"bytes,8,opt,name=upgrade,proto3,oneof"`
}

type ControlReply_Sendlogs struct {
	Sendlogs *SendLogsReply `protobuf:"bytes,9,opt,name=sendlogs,proto3,oneof"`
}

type ControlReply_Configure struct {
	Configure *ConfigureReply `protobuf:"bytes,10,opt,name=configure,proto3,oneof"`
}

type ControlReply_Import struct {
	Import *ImportReply `protobuf:"bytes,11,opt,name=import,proto3,oneof"`
}

type ControlReply_DriverConfig struct {
	DriverConfig *DriverConfigReply `protobuf:"bytes,12,opt,name=driver_config,json=driverConfig,proto3,oneof"`
}

type ControlReply_Validate struct {
	Validate *ValidateReply `protobuf:"bytes,13,opt,name=validate,proto3,oneof"`
}

func (*ControlReply_StreamAttach) isControlReply_Reply() {}

func (*ControlReply_Restart) isControlReply_Reply() {}

func (*ControlReply_Shutdown) isControlReply_Reply() {}

func (*ControlReply_Pause) isControlReply_Reply() {}

func (*ControlReply_Unpause) isControlReply_Reply() {}

func (*ControlReply_Upgrade) isControlReply_Reply() {}

func (*ControlReply_Sendlogs) isControlReply_Reply() {}

func (*ControlReply_Configure) isControlReply_Reply() {}

func (*ControlReply_Import) isControlReply_Reply() {}

func (*ControlReply_DriverConfig) isControlReply_Reply() {}

func (*ControlReply_Validate) isControlReply_Reply() {}

type StreamAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAttach) Reset() {
	*x = StreamAttach{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAttach) ProtoMessage() {}

func (x *StreamAttach) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAttach.ProtoReflect.Descriptor instead.
func (*StreamAttach) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{6}
}

type ShutdownReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownReply) Reset() {
	*x = ShutdownReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownReply) ProtoMessage() {}

func (x *ShutdownReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownReply.ProtoReflect.Descriptor instead.
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{7}
}

type RestartReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartReply) Reset() {
	*x = RestartReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartReply) ProtoMessage() {}

func (x *RestartReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartReply.ProtoReflect.Descriptor instead.
func (*RestartReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{8}
}

func (x *RestartReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestartReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PauseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseReply) Reset() {
	*x = PauseReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseReply) ProtoMessage() {}

func (x *PauseReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseReply.ProtoReflect.Descriptor instead.
func (*PauseReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{9}
}

func (x *PauseReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnpauseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpauseReply) Reset() {
	*x = UnpauseReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpauseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpauseReply) ProtoMessage() {}

func (x *UnpauseReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpauseReply.ProtoReflect.Descriptor instead.
func (*UnpauseReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{10}
}

func (x *UnpauseReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnpauseReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpgradeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeReply) Reset() {
	*x = UpgradeReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeReply) ProtoMessage() {}

func (x *UpgradeReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeReply.ProtoReflect.Descriptor instead.
func (*UpgradeReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{11}
}

func (x *UpgradeReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpgradeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogsReply) Reset() {
	*x = SendLogsReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogsReply) ProtoMessage() {}

func (x *SendLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogsReply.ProtoReflect.Descriptor instead.
func (*SendLogsReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{12}
}

type ConfigureReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MaskedUrl     string                 `protobuf:"bytes,3,opt,name=masked_url,json=maskedUrl,proto3" json:"masked_url,omitempty"`
	Backfill      bool                   `protobuf:"varint,4,opt,name=backfill,proto3" json:"backfill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureReply) Reset() {
	*x = ConfigureReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureReply) ProtoMessage() {}

func (x *ConfigureReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureReply.ProtoReflect.Descriptor instead.
func (*ConfigureReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigureReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigureReply) GetMaskedUrl() string {
	if x != nil {
		return x.MaskedUrl
	}
	return ""
}

func (x *ConfigureReply) GetBackfill() bool {
	if x != nil {
		return x.Backfill
	}
	return false
}

// Returns whether import initialized successfully; final result uses ImportResult
type ImportReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportReply) Reset() {
	*x = ImportReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportReply) ProtoMessage() {}

func (x *ImportReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportReply.ProtoReflect.Descriptor instead.
func (*ImportReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{14}
}

func (x *ImportReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImportReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DriverConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []byte                 `protobuf:"bytes,1,opt,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverConfigReply) Reset() {
	*x = DriverConfigReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverConfigReply) ProtoMessage() {}

func (x *DriverConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverConfigReply.ProtoReflect.Descriptor instead.
func (*DriverConfigReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{15}
}

func (x *DriverConfigReply) GetDrivers() []byte {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type ValidateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	FieldErrors   []*FieldError          `protobuf:"bytes,4,rep,name=field_errors,json=fieldErrors,proto3" json:"field_errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateReply) Reset() {
	*x = ValidateReply{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReply) ProtoMessage() {}

func (x *ValidateReply) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReply.ProtoReflect.Descriptor instead.
func (*ValidateReply) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ValidateReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ValidateReply) GetFieldErrors() []*FieldError {
	if x != nil {
		return x.FieldErrors
	}
	return nil
}

type FieldError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldError) Reset() {
	*x = FieldError{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldError) ProtoMessage() {}

func (x *FieldError) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldError.ProtoReflect.Descriptor instead.
func (*FieldError) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{17}
}

func (x *FieldError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Control commands: transmission -> EDS client
type ControlCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ControlCommand_Restart
	//	*ControlCommand_Shutdown
	//	*ControlCommand_Pause
	//	*ControlCommand_Unpause
	//	*ControlCommand_Upgrade
	//	*ControlCommand_Sendlogs
	//	*ControlCommand_Configure
	//	*ControlCommand_Import
	//	*ControlCommand_DriverConfig
	//	*ControlCommand_Validate
	Command       isControlCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{18}
}

func (x *ControlCommand) GetCommand() isControlCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ControlCommand) GetRestart() *Restart {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *ControlCommand) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ControlCommand) GetPause() *Pause {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *ControlCommand) GetUnpause() *Unpause {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Unpause); ok {
			return x.Unpause
		}
	}
	return nil
}

func (x *ControlCommand) GetUpgrade() *Upgrade {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Upgrade); ok {
			return x.Upgrade
		}
	}
	return nil
}

func (x *ControlCommand) GetSendlogs() *SendLogs {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Sendlogs); ok {
			return x.Sendlogs
		}
	}
	return nil
}

func (x *ControlCommand) GetConfigure() *Configure {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Configure); ok {
			return x.Configure
		}
	}
	return nil
}

func (x *ControlCommand) GetImport() *Import {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Import); ok {
			return x.Import
		}
	}
	return nil
}

func (x *ControlCommand) GetDriverConfig() *DriverConfig {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_DriverConfig); ok {
			return x.DriverConfig
		}
	}
	return nil
}

func (x *ControlCommand) GetValidate() *Validate {
	if x != nil {
		if x, ok := x.Command.(*ControlCommand_Validate); ok {
			return x.Validate
		}
	}
	return nil
}

type isControlCommand_Command interface {
	isControlCommand_Command()
}

type ControlCommand_Restart struct {
	Restart *Restart `protobuf:"bytes,1,opt,name=restart,proto3,oneof"`
}

type ControlCommand_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,2,opt,name=shutdown,proto3,oneof"`
}

type ControlCommand_Pause struct {
	Pause *Pause `protobuf:"bytes,3,opt,name=pause,proto3,oneof"`
}

type ControlCommand_Unpause struct {
	Unpause *Unpause `protobuf:"bytes,4,opt,name=unpause,proto3,oneof"`
}

type ControlCommand_Upgrade struct {
	Upgrade *Upgrade `protobuf:"bytes,5,opt,name=upgrade,proto3,oneof"`
}

type ControlCommand_Sendlogs struct {
	Sendlogs *SendLogs `protobuf:"bytes,6,opt,name=sendlogs,proto3,oneof"`
}

type ControlCommand_Configure struct {
	Configure *Configure `protobuf:"bytes,7,opt,name=configure,proto3,oneof"`
}

type ControlCommand_Import struct {
	Import *Import `protobuf:"bytes,8,opt,name=import,proto3,oneof"`
}

type ControlCommand_DriverConfig struct {
	DriverConfig *DriverConfig `protobuf:"bytes,9,opt,name=driver_config,json=driverConfig,proto3,oneof"`
}

type ControlCommand_Validate struct {
	Validate *Validate `protobuf:"bytes,10,opt,name=validate,proto3,oneof"`
}

func (*ControlCommand_Restart) isControlCommand_Command() {}

func (*ControlCommand_Shutdown) isControlCommand_Command() {}

func (*ControlCommand_Pause) isControlCommand_Command() {}

func (*ControlCommand_Unpause) isControlCommand_Command() {}

func (*ControlCommand_Upgrade) isControlCommand_Command() {}

func (*ControlCommand_Sendlogs) isControlCommand_Command() {}

func (*ControlCommand_Configure) isControlCommand_Command() {}

func (*ControlCommand_Import) isControlCommand_Command() {}

func (*ControlCommand_DriverConfig) isControlCommand_Command() {}

func (*ControlCommand_Validate) isControlCommand_Command() {}

type Restart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restart) Reset() {
	*x = Restart{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restart) ProtoMessage() {}

func (x *Restart) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restart.ProtoReflect.Descriptor instead.
func (*Restart) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{19}
}

type Pause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pause) Reset() {
	*x = Pause{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pause) ProtoMessage() {}

func (x *Pause) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pause.ProtoReflect.Descriptor instead.
func (*Pause) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{20}
}

type Unpause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unpause) Reset() {
	*x = Unpause{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unpause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unpause) ProtoMessage() {}

func (x *Unpause) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unpause.ProtoReflect.Descriptor instead.
func (*Unpause) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{21}
}

type SendLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogs) Reset() {
	*x = SendLogs{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogs) ProtoMessage() {}

func (x *SendLogs) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogs.ProtoReflect.Descriptor instead.
func (*SendLogs) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{22}
}

type DriverConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverConfig) Reset() {
	*x = DriverConfig{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverConfig) ProtoMessage() {}

func (x *DriverConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverConfig.ProtoReflect.Descriptor instead.
func (*DriverConfig) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{23}
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{24}
}

func (x *Shutdown) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Shutdown) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type Upgrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upgrade) Reset() {
	*x = Upgrade{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upgrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upgrade) ProtoMessage() {}

func (x *Upgrade) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upgrade.ProtoReflect.Descriptor instead.
func (*Upgrade) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{25}
}

func (x *Upgrade) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Configure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Backfill      bool                   `protobuf:"varint,2,opt,name=backfill,proto3" json:"backfill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configure) Reset() {
	*x = Configure{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configure) ProtoMessage() {}

func (x *Configure) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configure.ProtoReflect.Descriptor instead.
func (*Configure) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{26}
}

func (x *Configure) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Configure) GetBackfill() bool {
	if x != nil {
		return x.Backfill
	}
	return false
}

type Import struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backfill      bool                   `protobuf:"varint,1,opt,name=backfill,proto3" json:"backfill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Import) Reset() {
	*x = Import{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Import.ProtoReflect.Descriptor instead.
func (*Import) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{27}
}

func (x *Import) GetBackfill() bool {
	if x != nil {
		return x.Backfill
	}
	return false
}

type Validate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validate) Reset() {
	*x = Validate{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validate) ProtoMessage() {}

func (x *Validate) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validate.ProtoReflect.Descriptor instead.
func (*Validate) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{28}
}

func (x *Validate) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Validate) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// PSLC = PublishSendLogsComplete
type PSLCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdsId         string                 `protobuf:"bytes,1,opt,name=eds_id,json=edsId,proto3" json:"eds_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSLCRequest) Reset() {
	*x = PSLCRequest{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSLCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSLCRequest) ProtoMessage() {}

func (x *PSLCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSLCRequest.ProtoReflect.Descriptor instead.
func (*PSLCRequest) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{29}
}

func (x *PSLCRequest) GetEdsId() string {
	if x != nil {
		return x.EdsId
	}
	return ""
}

func (x *PSLCRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PSLCRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PSLCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PSLCResponse) Reset() {
	*x = PSLCResponse{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PSLCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSLCResponse) ProtoMessage() {}

func (x *PSLCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSLCResponse.ProtoReflect.Descriptor instead.
func (*PSLCResponse) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{30}
}

type SendStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdsId         string                 `protobuf:"bytes,1,opt,name=eds_id,json=edsId,proto3" json:"eds_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action        StatusAction           `protobuf:"varint,3,opt,name=action,proto3,enum=shopmonkey.transmission.v1.StatusAction" json:"action,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStatusRequest) Reset() {
	*x = SendStatusRequest{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStatusRequest) ProtoMessage() {}

func (x *SendStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStatusRequest.ProtoReflect.Descriptor instead.
func (*SendStatusRequest) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{31}
}

func (x *SendStatusRequest) GetEdsId() string {
	if x != nil {
		return x.EdsId
	}
	return ""
}

func (x *SendStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendStatusRequest) GetAction() StatusAction {
	if x != nil {
		return x.Action
	}
	return StatusAction_STATUS_ACTION_UNSPECIFIED
}

func (x *SendStatusRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStatusResponse) Reset() {
	*x = SendStatusResponse{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStatusResponse) ProtoMessage() {}

func (x *SendStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStatusResponse.ProtoReflect.Descriptor instead.
func (*SendStatusResponse) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{32}
}

type ImportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResultRequest) Reset() {
	*x = ImportResultRequest{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResultRequest) ProtoMessage() {}

func (x *ImportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResultRequest.ProtoReflect.Descriptor instead.
func (*ImportResultRequest) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{33}
}

func (x *ImportResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImportResultRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ImportResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ImportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResultResponse) Reset() {
	*x = ImportResultResponse{}
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResultResponse) ProtoMessage() {}

func (x *ImportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopmonkey_transmission_v1_stream_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResultResponse.ProtoReflect.Descriptor instead.
func (*ImportResultResponse) Descriptor() ([]byte, []int) {
	return file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP(), []int{34}
}

var File_shopmonkey_transmission_v1_stream_proto protoreflect.FileDescriptor

const file_shopmonkey_transmission_v1_stream_proto_rawDesc = "" +
	"\n" +
	"'shopmonkey/transmission/v1/stream.proto\x12\x1ashopmonkey.transmission.v1\x1a\x1cgoogle/protobuf/struct.proto\"a\n" +
	"\fFetchRequest\x12\x1b\n" +
	"\tmax_count\x18\x01 \x01(\x05R\bmaxCount\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\x12\x15\n" +
	"\x06eds_id\x18\x03 \x01(\tR\x05edsId\"V\n" +
	"\rFetchResponse\x12E\n" +
	"\bmessages\x18\x01 \x03(\v2).shopmonkey.transmission.v1.ChangeMessageR\bmessages\")\n" +
	"\rChangeMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"7\n" +
	"\n" +
	"LogRequest\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\x12\x15\n" +
	"\x06eds_id\x18\x02 \x01(\tR\x05edsId\"\r\n" +
	"\vLogResponse\"\xf0\x06\n" +
	"\fControlReply\x12\x15\n" +
	"\x06eds_id\x18\x01 \x01(\tR\x05edsId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12O\n" +
	"\rstream_attach\x18\x03 \x01(\v2(.shopmonkey.transmission.v1.StreamAttachH\x00R\fstreamAttach\x12D\n" +
	"\arestart\x18\x04 \x01(\v2(.shopmonkey.transmission.v1.RestartReplyH\x00R\arestart\x12G\n" +
	"\bshutdown\x18\x05 \x01(\v2).shopmonkey.transmission.v1.ShutdownReplyH\x00R\bshutdown\x12>\n" +
	"\x05pause\x18\x06 \x01(\v2&.shopmonkey.transmission.v1.PauseReplyH\x00R\x05pause\x12D\n" +
	"\aunpause\x18\a \x01(\v2(.shopmonkey.transmission.v1.UnpauseReplyH\x00R\aunpause\x12D\n" +
	"\aupgrade\x18\b \x01(\v2(.shopmonkey.transmission.v1.UpgradeReplyH\x00R\aupgrade\x12G\n" +
	"\bsendlogs\x18\t \x01(\v2).shopmonkey.transmission.v1.SendLogsReplyH\x00R\bsendlogs\x12J\n" +
	"\tconfigure\x18\n" +
	" \x01(\v2*.shopmonkey.transmission.v1.ConfigureReplyH\x00R\tconfigure\x12A\n" +
	"\x06import\x18\v \x01(\v2'.shopmonkey.transmission.v1.ImportReplyH\x00R\x06import\x12T\n" +
	"\rdriver_config\x18\f \x01(\v2-.shopmonkey.transmission.v1.DriverConfigReplyH\x00R\fdriverConfig\x12G\n" +
	"\bvalidate\x18\r \x01(\v2).shopmonkey.transmission.v1.ValidateReplyH\x00R\bvalidateB\a\n" +
	"\x05reply\"\x0e\n" +
	"\fStreamAttach\"\x0f\n" +
	"\rShutdownReply\"B\n" +
	"\fRestartReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\n" +
	"PauseReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\fUnpauseReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\fUpgradeReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rSendLogsReply\"\x7f\n" +
	"\x0eConfigureReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"masked_url\x18\x03 \x01(\tR\tmaskedUrl\x12\x1a\n" +
	"\bbackfill\x18\x04 \x01(\bR\bbackfill\"A\n" +
	"\vImportReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x11DriverConfigReply\x12\x18\n" +
	"\adrivers\x18\x01 \x01(\fR\adrivers\"\xa0\x01\n" +
	"\rValidateReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12I\n" +
	"\ffield_errors\x18\x04 \x03(\v2&.shopmonkey.transmission.v1.FieldErrorR\vfieldErrors\"<\n" +
	"\n" +
	"FieldError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x05\n" +
	"\x0eControlCommand\x12?\n" +
	"\arestart\x18\x01 \x01(\v2#.shopmonkey.transmission.v1.RestartH\x00R\arestart\x12B\n" +
	"\bshutdown\x18\x02 \x01(\v2$.shopmonkey.transmission.v1.ShutdownH\x00R\bshutdown\x129\n" +
	"\x05pause\x18\x03 \x01(\v2!.shopmonkey.transmission.v1.PauseH\x00R\x05pause\x12?\n" +
	"\aunpause\x18\x04 \x01(\v2#.shopmonkey.transmission.v1.UnpauseH\x00R\aunpause\x12?\n" +
	"\aupgrade\x18\x05 \x01(\v2#.shopmonkey.transmission.v1.UpgradeH\x00R\aupgrade\x12B\n" +
	"\bsendlogs\x18\x06 \x01(\v2$.shopmonkey.transmission.v1.SendLogsH\x00R\bsendlogs\x12E\n" +
	"\tconfigure\x18\a \x01(\v2%.shopmonkey.transmission.v1.ConfigureH\x00R\tconfigure\x12<\n" +
	"\x06import\x18\b \x01(\v2\".shopmonkey.transmission.v1.ImportH\x00R\x06import\x12O\n" +
	"\rdriver_config\x18\t \x01(\v2(.shopmonkey.transmission.v1.DriverConfigH\x00R\fdriverConfig\x12B\n" +
	"\bvalidate\x18\n" +
	" \x01(\v2$.shopmonkey.transmission.v1.ValidateH\x00R\bvalidateB\t\n" +
	"\acommand\"\t\n" +
	"\aRestart\"\a\n" +
	"\x05Pause\"\t\n" +
	"\aUnpause\"\n" +
	"\n" +
	"\bSendLogs\"\x0e\n" +
	"\fDriverConfig\">\n" +
	"\bShutdown\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"#\n" +
	"\aUpgrade\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"9\n" +
	"\tConfigure\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bbackfill\x18\x02 \x01(\bR\bbackfill\"$\n" +
	"\x06Import\x12\x1a\n" +
	"\bbackfill\x18\x01 \x01(\bR\bbackfill\"S\n" +
	"\bValidate\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\"W\n" +
	"\vPSLCRequest\x12\x15\n" +
	"\x06eds_id\x18\x01 \x01(\tR\x05edsId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\x0e\n" +
	"\fPSLCResponse\"\xbf\x01\n" +
	"\x11SendStatusRequest\x12\x15\n" +
	"\x06eds_id\x18\x01 \x01(\tR\x05edsId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12@\n" +
	"\x06action\x18\x03 \x01(\x0e2(.shopmonkey.transmission.v1.StatusActionR\x06action\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x14\n" +
	"\x12SendStatusResponse\"h\n" +
	"\x13ImportResultRequest\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x16\n" +
	"\x14ImportResultResponse*}\n" +
	"\fStatusAction\x12\x1d\n" +
	"\x19STATUS_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STATUS_ACTION_RESTART\x10\x01\x12\x19\n" +
	"\x15STATUS_ACTION_UPGRADE\x10\x02\x12\x18\n" +
	"\x14STATUS_ACTION_IMPORT\x10\x032\x80\x05\n" +
	"\x13TransmissionService\x12^\n" +
	"\x05Fetch\x12(.shopmonkey.transmission.v1.FetchRequest\x1a).shopmonkey.transmission.v1.FetchResponse0\x01\x12V\n" +
	"\x03Log\x12&.shopmonkey.transmission.v1.LogRequest\x1a'.shopmonkey.transmission.v1.LogResponse\x12c\n" +
	"\aControl\x12(.shopmonkey.transmission.v1.ControlReply\x1a*.shopmonkey.transmission.v1.ControlCommand(\x010\x01\x12l\n" +
	"\x17PublishSendLogsComplete\x12'.shopmonkey.transmission.v1.PSLCRequest\x1a(.shopmonkey.transmission.v1.PSLCResponse\x12k\n" +
	"\n" +
	"SendStatus\x12-.shopmonkey.transmission.v1.SendStatusRequest\x1a..shopmonkey.transmission.v1.SendStatusResponse\x12q\n" +
	"\fImportResult\x12/.shopmonkey.transmission.v1.ImportResultRequest\x1a0.shopmonkey.transmission.v1.ImportResultResponseB@Z>github.com/shopmonkeyus/eds/pkg/transmission/v1;transmissionv1b\x06proto3"

var (
	file_shopmonkey_transmission_v1_stream_proto_rawDescOnce sync.Once
	file_shopmonkey_transmission_v1_stream_proto_rawDescData []byte
)

func file_shopmonkey_transmission_v1_stream_proto_rawDescGZIP() []byte {
	file_shopmonkey_transmission_v1_stream_proto_rawDescOnce.Do(func() {
		file_shopmonkey_transmission_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shopmonkey_transmission_v1_stream_proto_rawDesc), len(file_shopmonkey_transmission_v1_stream_proto_rawDesc)))
	})
	return file_shopmonkey_transmission_v1_stream_proto_rawDescData
}

var file_shopmonkey_transmission_v1_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shopmonkey_transmission_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_shopmonkey_transmission_v1_stream_proto_goTypes = []any{
	(StatusAction)(0),            // 0: shopmonkey.transmission.v1.StatusAction
	(*FetchRequest)(nil),         // 1: shopmonkey.transmission.v1.FetchRequest
	(*FetchResponse)(nil),        // 2: shopmonkey.transmission.v1.FetchResponse
	(*ChangeMessage)(nil),        // 3: shopmonkey.transmission.v1.ChangeMessage
	(*LogRequest)(nil),           // 4: shopmonkey.transmission.v1.LogRequest
	(*LogResponse)(nil),          // 5: shopmonkey.transmission.v1.LogResponse
	(*ControlReply)(nil),         // 6: shopmonkey.transmission.v1.ControlReply
	(*StreamAttach)(nil),         // 7: shopmonkey.transmission.v1.StreamAttach
	(*ShutdownReply)(nil),        // 8: shopmonkey.transmission.v1.ShutdownReply
	(*RestartReply)(nil),         // 9: shopmonkey.transmission.v1.RestartReply
	(*PauseReply)(nil),           // 10: shopmonkey.transmission.v1.PauseReply
	(*UnpauseReply)(nil),         // 11: shopmonkey.transmission.v1.UnpauseReply
	(*UpgradeReply)(nil),         // 12: shopmonkey.transmission.v1.UpgradeReply
	(*SendLogsReply)(nil),        // 13: shopmonkey.transmission.v1.SendLogsReply
	(*ConfigureReply)(nil),       // 14: shopmonkey.transmission.v1.ConfigureReply
	(*ImportReply)(nil),          // 15: shopmonkey.transmission.v1.ImportReply
	(*DriverConfigReply)(nil),    // 16: shopmonkey.transmission.v1.DriverConfigReply
	(*ValidateReply)(nil),        // 17: shopmonkey.transmission.v1.ValidateReply
	(*FieldError)(nil),           // 18: shopmonkey.transmission.v1.FieldError
	(*ControlCommand)(nil),       // 19: shopmonkey.transmission.v1.ControlCommand
	(*Restart)(nil),              // 20: shopmonkey.transmission.v1.Restart
	(*Pause)(nil),                // 21: shopmonkey.transmission.v1.Pause
	(*Unpause)(nil),              // 22: shopmonkey.transmission.v1.Unpause
	(*SendLogs)(nil),             // 23: shopmonkey.transmission.v1.SendLogs
	(*DriverConfig)(nil),         // 24: shopmonkey.transmission.v1.DriverConfig
	(*Shutdown)(nil),             // 25: shopmonkey.transmission.v1.Shutdown
	(*Upgrade)(nil),              // 26: shopmonkey.transmission.v1.Upgrade
	(*Configure)(nil),            // 27: shopmonkey.transmission.v1.Configure
	(*Import)(nil),               // 28: shopmonkey.transmission.v1.Import
	(*Validate)(nil),             // 29: shopmonkey.transmission.v1.Validate
	(*PSLCRequest)(nil),          // 30: shopmonkey.transmission.v1.PSLCRequest
	(*PSLCResponse)(nil),         // 31: shopmonkey.transmission.v1.PSLCResponse
	(*SendStatusRequest)(nil),    // 32: shopmonkey.transmission.v1.SendStatusRequest
	(*SendStatusResponse)(nil),   // 33: shopmonkey.transmission.v1.SendStatusResponse
	(*ImportResultRequest)(nil),  // 34: shopmonkey.transmission.v1.ImportResultRequest
	(*ImportResultResponse)(nil), // 35: shopmonkey.transmission.v1.ImportResultResponse
	(*structpb.Struct)(nil),      // 36: google.protobuf.Struct
}
var file_shopmonkey_transmission_v1_stream_proto_depIdxs = []int32{
	3,  // 0: shopmonkey.transmission.v1.FetchResponse.messages:type_name -> shopmonkey.transmission.v1.ChangeMessage
	7,  // 1: shopmonkey.transmission.v1.ControlReply.stream_attach:type_name -> shopmonkey.transmission.v1.StreamAttach
	9,  // 2: shopmonkey.transmission.v1.ControlReply.restart:type_name -> shopmonkey.transmission.v1.RestartReply
	8,  // 3: shopmonkey.transmission.v1.ControlReply.shutdown:type_name -> shopmonkey.transmission.v1.ShutdownReply
	10, // 4: shopmonkey.transmission.v1.ControlReply.pause:type_name -> shopmonkey.transmission.v1.PauseReply
	11, // 5: shopmonkey.transmission.v1.ControlReply.unpause:type_name -> shopmonkey.transmission.v1.UnpauseReply
	12, // 6: shopmonkey.transmission.v1.ControlReply.upgrade:type_name -> shopmonkey.transmission.v1.UpgradeReply
	13, // 7: shopmonkey.transmission.v1.ControlReply.sendlogs:type_name -> shopmonkey.transmission.v1.SendLogsReply
	14, // 8: shopmonkey.transmission.v1.ControlReply.configure:type_name -> shopmonkey.transmission.v1.ConfigureReply
	15, // 9: shopmonkey.transmission.v1.ControlReply.import:type_name -> shopmonkey.transmission.v1.ImportReply
	16, // 10: shopmonkey.transmission.v1.ControlReply.driver_config:type_name -> shopmonkey.transmission.v1.DriverConfigReply
	17, // 11: shopmonkey.transmission.v1.ControlReply.validate:type_name -> shopmonkey.transmission.v1.ValidateReply
	18, // 12: shopmonkey.transmission.v1.ValidateReply.field_errors:type_name -> shopmonkey.transmission.v1.FieldError
	20, // 13: shopmonkey.transmission.v1.ControlCommand.restart:type_name -> shopmonkey.transmission.v1.Restart
	25, // 14: shopmonkey.transmission.v1.ControlCommand.shutdown:type_name -> shopmonkey.transmission.v1.Shutdown
	21, // 15: shopmonkey.transmission.v1.ControlCommand.pause:type_name -> shopmonkey.transmission.v1.Pause
	22, // 16: shopmonkey.transmission.v1.ControlCommand.unpause:type_name -> shopmonkey.transmission.v1.Unpause
	26, // 17: shopmonkey.transmission.v1.ControlCommand.upgrade:type_name -> shopmonkey.transmission.v1.Upgrade
	23, // 18: shopmonkey.transmission.v1.ControlCommand.sendlogs:type_name -> shopmonkey.transmission.v1.SendLogs
	27, // 19: shopmonkey.transmission.v1.ControlCommand.configure:type_name -> shopmonkey.transmission.v1.Configure
	28, // 20: shopmonkey.transmission.v1.ControlCommand.import:type_name -> shopmonkey.transmission.v1.Import
	24, // 21: shopmonkey.transmission.v1.ControlCommand.driver_config:type_name -> shopmonkey.transmission.v1.DriverConfig
	29, // 22: shopmonkey.transmission.v1.ControlCommand.validate:type_name -> shopmonkey.transmission.v1.Validate
	36, // 23: shopmonkey.transmission.v1.Validate.config:type_name -> google.protobuf.Struct
	0,  // 24: shopmonkey.transmission.v1.SendStatusRequest.action:type_name -> shopmonkey.transmission.v1.StatusAction
	1,  // 25: shopmonkey.transmission.v1.TransmissionService.Fetch:input_type -> shopmonkey.transmission.v1.FetchRequest
	4,  // 26: shopmonkey.transmission.v1.TransmissionService.Log:input_type -> shopmonkey.transmission.v1.LogRequest
	6,  // 27: shopmonkey.transmission.v1.TransmissionService.Control:input_type -> shopmonkey.transmission.v1.ControlReply
	30, // 28: shopmonkey.transmission.v1.TransmissionService.PublishSendLogsComplete:input_type -> shopmonkey.transmission.v1.PSLCRequest
	32, // 29: shopmonkey.transmission.v1.TransmissionService.SendStatus:input_type -> shopmonkey.transmission.v1.SendStatusRequest
	34, // 30: shopmonkey.transmission.v1.TransmissionService.ImportResult:input_type -> shopmonkey.transmission.v1.ImportResultRequest
	2,  // 31: shopmonkey.transmission.v1.TransmissionService.Fetch:output_type -> shopmonkey.transmission.v1.FetchResponse
	5,  // 32: shopmonkey.transmission.v1.TransmissionService.Log:output_type -> shopmonkey.transmission.v1.LogResponse
	19, // 33: shopmonkey.transmission.v1.TransmissionService.Control:output_type -> shopmonkey.transmission.v1.ControlCommand
	31, // 34: shopmonkey.transmission.v1.TransmissionService.PublishSendLogsComplete:output_type -> shopmonkey.transmission.v1.PSLCResponse
	33, // 35: shopmonkey.transmission.v1.TransmissionService.SendStatus:output_type -> shopmonkey.transmission.v1.SendStatusResponse
	35, // 36: shopmonkey.transmission.v1.TransmissionService.ImportResult:output_type -> shopmonkey.transmission.v1.ImportResultResponse
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_shopmonkey_transmission_v1_stream_proto_init() }
func file_shopmonkey_transmission_v1_stream_proto_init() {
	if File_shopmonkey_transmission_v1_stream_proto != nil {
		return
	}
	file_shopmonkey_transmission_v1_stream_proto_msgTypes[5].OneofWrappers = []any{
		(*ControlReply_StreamAttach)(nil),
		(*ControlReply_Restart)(nil),
		(*ControlReply_Shutdown)(nil),
		(*ControlReply_Pause)(nil),
		(*ControlReply_Unpause)(nil),
		(*ControlReply_Upgrade)(nil),
		(*ControlReply_Sendlogs)(nil),
		(*ControlReply_Configure)(nil),
		(*ControlReply_Import)(nil),
		(*ControlReply_DriverConfig)(nil),
		(*ControlReply_Validate)(nil),
	}
	file_shopmonkey_transmission_v1_stream_proto_msgTypes[18].OneofWrappers = []any{
		(*ControlCommand_Restart)(nil),
		(*ControlCommand_Shutdown)(nil),
		(*ControlCommand_Pause)(nil),
		(*ControlCommand_Unpause)(nil),
		(*ControlCommand_Upgrade)(nil),
		(*ControlCommand_Sendlogs)(nil),
		(*ControlCommand_Configure)(nil),
		(*ControlCommand_Import)(nil),
		(*ControlCommand_DriverConfig)(nil),
		(*ControlCommand_Validate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shopmonkey_transmission_v1_stream_proto_rawDesc), len(file_shopmonkey_transmission_v1_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopmonkey_transmission_v1_stream_proto_goTypes,
		DependencyIndexes: file_shopmonkey_transmission_v1_stream_proto_depIdxs,
		EnumInfos:         file_shopmonkey_transmission_v1_stream_proto_enumTypes,
		MessageInfos:      file_shopmonkey_transmission_v1_stream_proto_msgTypes,
	}.Build()
	File_shopmonkey_transmission_v1_stream_proto = out.File
	file_shopmonkey_transmission_v1_stream_proto_goTypes = nil
	file_shopmonkey_transmission_v1_stream_proto_depIdxs = nil
}
