// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: shopmonkey/transmission/v1/stream.proto

package transmissionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransmissionService_Fetch_FullMethodName                   = "/shopmonkey.transmission.v1.TransmissionService/Fetch"
	TransmissionService_Log_FullMethodName                     = "/shopmonkey.transmission.v1.TransmissionService/Log"
	TransmissionService_Control_FullMethodName                 = "/shopmonkey.transmission.v1.TransmissionService/Control"
	TransmissionService_PublishSendLogsComplete_FullMethodName = "/shopmonkey.transmission.v1.TransmissionService/PublishSendLogsComplete"
	TransmissionService_SendStatus_FullMethodName              = "/shopmonkey.transmission.v1.TransmissionService/SendStatus"
	TransmissionService_ImportResult_FullMethodName            = "/shopmonkey.transmission.v1.TransmissionService/ImportResult"
)

// TransmissionServiceClient is the client API for TransmissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransmissionServiceClient interface {
	// needs stream to handle large batches of messages
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	// Control is used for syncronous commands pushed to the client
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlReply, ControlCommand], error)
	PublishSendLogsComplete(ctx context.Context, in *PSLCRequest, opts ...grpc.CallOption) (*PSLCResponse, error)
	SendStatus(ctx context.Context, in *SendStatusRequest, opts ...grpc.CallOption) (*SendStatusResponse, error)
	ImportResult(ctx context.Context, in *ImportResultRequest, opts ...grpc.CallOption) (*ImportResultResponse, error)
}

type transmissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransmissionServiceClient(cc grpc.ClientConnInterface) TransmissionServiceClient {
	return &transmissionServiceClient{cc}
}

func (c *transmissionServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransmissionService_ServiceDesc.Streams[0], TransmissionService_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransmissionService_FetchClient = grpc.ServerStreamingClient[FetchResponse]

func (c *transmissionServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, TransmissionService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transmissionServiceClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlReply, ControlCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransmissionService_ServiceDesc.Streams[1], TransmissionService_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlReply, ControlCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransmissionService_ControlClient = grpc.BidiStreamingClient[ControlReply, ControlCommand]

func (c *transmissionServiceClient) PublishSendLogsComplete(ctx context.Context, in *PSLCRequest, opts ...grpc.CallOption) (*PSLCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PSLCResponse)
	err := c.cc.Invoke(ctx, TransmissionService_PublishSendLogsComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transmissionServiceClient) SendStatus(ctx context.Context, in *SendStatusRequest, opts ...grpc.CallOption) (*SendStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendStatusResponse)
	err := c.cc.Invoke(ctx, TransmissionService_SendStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transmissionServiceClient) ImportResult(ctx context.Context, in *ImportResultRequest, opts ...grpc.CallOption) (*ImportResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportResultResponse)
	err := c.cc.Invoke(ctx, TransmissionService_ImportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransmissionServiceServer is the server API for TransmissionService service.
// All implementations must embed UnimplementedTransmissionServiceServer
// for forward compatibility.
type TransmissionServiceServer interface {
	// needs stream to handle large batches of messages
	Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error
	Log(context.Context, *LogRequest) (*LogResponse, error)
	// Control is used for syncronous commands pushed to the client
	Control(grpc.BidiStreamingServer[ControlReply, ControlCommand]) error
	PublishSendLogsComplete(context.Context, *PSLCRequest) (*PSLCResponse, error)
	SendStatus(context.Context, *SendStatusRequest) (*SendStatusResponse, error)
	ImportResult(context.Context, *ImportResultRequest) (*ImportResultResponse, error)
	mustEmbedUnimplementedTransmissionServiceServer()
}

// UnimplementedTransmissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransmissionServiceServer struct{}

func (UnimplementedTransmissionServiceServer) Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error {
	return status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedTransmissionServiceServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedTransmissionServiceServer) Control(grpc.BidiStreamingServer[ControlReply, ControlCommand]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedTransmissionServiceServer) PublishSendLogsComplete(context.Context, *PSLCRequest) (*PSLCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSendLogsComplete not implemented")
}
func (UnimplementedTransmissionServiceServer) SendStatus(context.Context, *SendStatusRequest) (*SendStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendStatus not implemented")
}
func (UnimplementedTransmissionServiceServer) ImportResult(context.Context, *ImportResultRequest) (*ImportResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportResult not implemented")
}
func (UnimplementedTransmissionServiceServer) mustEmbedUnimplementedTransmissionServiceServer() {}
func (UnimplementedTransmissionServiceServer) testEmbeddedByValue()                             {}

// UnsafeTransmissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransmissionServiceServer will
// result in compilation errors.
type UnsafeTransmissionServiceServer interface {
	mustEmbedUnimplementedTransmissionServiceServer()
}

func RegisterTransmissionServiceServer(s grpc.ServiceRegistrar, srv TransmissionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransmissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransmissionService_ServiceDesc, srv)
}

func _TransmissionService_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransmissionServiceServer).Fetch(m, &grpc.GenericServerStream[FetchRequest, FetchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransmissionService_FetchServer = grpc.ServerStreamingServer[FetchResponse]

func _TransmissionService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmissionServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransmissionService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmissionServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransmissionService_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransmissionServiceServer).Control(&grpc.GenericServerStream[ControlReply, ControlCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransmissionService_ControlServer = grpc.BidiStreamingServer[ControlReply, ControlCommand]

func _TransmissionService_PublishSendLogsComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PSLCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmissionServiceServer).PublishSendLogsComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransmissionService_PublishSendLogsComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmissionServiceServer).PublishSendLogsComplete(ctx, req.(*PSLCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransmissionService_SendStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmissionServiceServer).SendStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransmissionService_SendStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmissionServiceServer).SendStatus(ctx, req.(*SendStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransmissionService_ImportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransmissionServiceServer).ImportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransmissionService_ImportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransmissionServiceServer).ImportResult(ctx, req.(*ImportResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransmissionService_ServiceDesc is the grpc.ServiceDesc for TransmissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransmissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shopmonkey.transmission.v1.TransmissionService",
	HandlerType: (*TransmissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _TransmissionService_Log_Handler,
		},
		{
			MethodName: "PublishSendLogsComplete",
			Handler:    _TransmissionService_PublishSendLogsComplete_Handler,
		},
		{
			MethodName: "SendStatus",
			Handler:    _TransmissionService_SendStatus_Handler,
		},
		{
			MethodName: "ImportResult",
			Handler:    _TransmissionService_ImportResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fetch",
			Handler:       _TransmissionService_Fetch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Control",
			Handler:       _TransmissionService_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "shopmonkey/transmission/v1/stream.proto",
}
