#!/bin/bash

docker compose down --remove-orphans
docker-compose up -d

# Set a flag to indicate whether the command was successful
success=false

# Loop until the command is successful or the maximum number of attempts is reached
while [ $success = false ]; do
  # Execute the command
  QUERY=$(cat <<- EOF
    IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'shopmonkey')
    BEGIN
        CREATE DATABASE shopmonkey;
    END;
EOF
    )
    echo $QUERY
  #Some people may have localhost set up correctly, so may not need the "-S 127.0.0.1" part
  sqlcmd -S 127.0.0.1 -C -U sa -P Asdf1234! -d tempdb -Q "$QUERY" 
  # Check the exit code of the command
  if [ $? -eq 0 ]; then
    # The command was successful
    success=true
  else
    sleep 10
  fi
done
