syntax = "proto3";

package shopmonkey.transmission.v1;

import "google/protobuf/struct.proto";

option go_package = "github.com/shopmonkeyus/eds/pkg/transmission/v1;transmissionv1";

service TransmissionService {
  rpc Fetch(FetchRequest) returns (stream FetchResponse);

  rpc Log(LogRequest) returns (LogResponse);

  rpc Control(stream ControlRequest) returns (stream ControlResponse);

  rpc SendLogs(SendLogsRequest) returns (SendLogsResponse);

  rpc Status(StatusRequest) returns (StatusResponse);

  rpc ImportResult(ImportResultRequest) returns (ImportResultResponse);
}

message FetchRequest {
  int32 max_count = 1;
  int64 timeout_ms = 2;
  string eds_id = 3;
}

message FetchResponse {
  repeated ChangeMessage messages = 1;
}

message ChangeMessage {
  bytes payload = 1;
}

message LogRequest {
  bytes json = 1;
  string eds_id = 2;
}

message LogResponse {}

message ControlRequest {
  string eds_id = 1;
  string session_id = 2;
  google.protobuf.Struct payload = 3;
}

message ControlResponse {
  string action = 1;

  google.protobuf.Struct payload = 2;
}

message SendLogsRequest {
  string eds_id = 1;
  string session_id = 2;
  string path = 3;
}

message SendLogsResponse {}

message StatusRequest {
  string eds_id = 1;
  string session_id = 2;
  string action = 3;

  google.protobuf.Struct payload = 4;
}

message StatusResponse {}

message ImportResultRequest {
  bool success = 1;
  string message = 2;
  string job_id = 3;
  string session_id = 4;
}

message ImportResultResponse {}
